name: Anan-vue Master Dockerfile CI
env:
  MODULE_NAME: anan-vue
  MODULE_VERSION: 3.0.0
  MODULE_PROFILE: prod
  MODULE_PATH: .
on:
  push:
    branches:
      - master
    paths:
      - $MODULE_PATH/**
  pull_request:
    branches:
      - master
    paths:
      - $MODULE_PATH/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branche
        uses: actions/checkout@v2
        with:
          ref: 'master'
      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: '11.x'
      - name: Install Dependencies
        run: npm install
      - name: Build with Node
        run: |
          npm run build:prod
      - name: Docker build and push image
        run: |
          docker login --username=${{ secrets.dockerhub_user }} --password=${{ secrets.dockerhub_pass }}
          docker build $MODULE_PATH -t fosin/$MODULE_NAME:$MODULE_VERSION -f $MODULE_PATH/Dockerfile
          docker push fosin/$MODULE_NAME:$MODULE_VERSION
          docker logout
