name: anan-vue Dockerfile CI
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set env
        run: echo ::set-env name=MODULE_VERSION::$(echo ${GITHUB_REF:10})

      - name: Checkout branche
        uses: actions/checkout@v2
        with:
          # The branch, tag or SHA to checkout. When checking out the repository that
          # triggered a workflow, this defaults to the reference or SHA for that event.
          # Otherwise, defaults to `master`.
          ref: ${{ env.MODULE_VERSION }}

      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: '11.x'

      - name: Install Dependencies
        run: |
          npm install @vue/cli
          npm install babel-plugin-dynamic-import-node -S -D
          npm install

      - name: Build with Node
        run: |
          npm run build:prod

      - name: Docker build and push image
        env:
          MODULE_PATH: .
          MODULE_NAME: anan-vue
        run: |
          docker login --username=${{ secrets.dockerhub_user }} --password=${{ secrets.dockerhub_pass }}
          docker build $MODULE_PATH -t fosin/$MODULE_NAME:$MODULE_VERSION -f $MODULE_PATH/Dockerfile
          docker push fosin/$MODULE_NAME:$MODULE_VERSION
          docker logout
